;;; sz-ewm-status-test.el --- ERT checks for cached EWM status -*- lexical-binding: t -*-

;; Reuse the pinned upstream Lisp harness and its clearly labelled native-module
;; mocks.  These checks exercise the local collector layer, never a live bus.
(load (expand-file-name "sz-ewm-test.el" (file-name-directory load-file-name))
      nil 'nomessage t)

(require 'ert)
(require 'cl-lib)

(ert-deftest sz/ewm-status-audio-format-preserves-mute-and-microphone-meaning ()
  (should (equal (sz/ewm-status--audio-value '(:volume 0.52 :muted nil)
                                            '(:volume 0 :muted nil))
                 "52% audio +MIC"))
  (should (equal (sz/ewm-status--audio-value '(:volume 1 :muted t)
                                            '(:volume 0 :muted t))
                 "MUTED"))
  (should-not (sz/ewm-status--parse-wpctl "unexpected")))

(ert-deftest sz/ewm-status-network-failure-and-normal-states ()
  (should (equal (sz/ewm-status--network-string nil t t) "network?"))
  (should (equal (sz/ewm-status--network-string nil nil t) "network?"))
  (should (equal (sz/ewm-status--network-string
                  (list '(:type 2 :state 30 :interface "wlan0")) nil t)
                 "Wi-Fi disabled"))
  (should (equal (sz/ewm-status--network-string
                  (list '(:type 1 :state 100 :interface "eth0" :ip4 nil)) t t)
                 "eth0 (No IP)"))
  (should (equal (sz/ewm-status--network-string
                  (list '(:type 2 :state 100 :interface "wlan0" :ip4 t :strength 19)) t t)
                 "<20% wlan"))
  (should (equal (sz/ewm-status--network-string
                  (list '(:type 1 :state 100 :interface "eth0" :ip4 t)) t t)
                 "")))

(ert-deftest sz/ewm-status-xkb-advice-updates-only-xkb-events ()
  (let ((sz/ewm-status-layout "") unrelated)
    (sz/ewm-status--handle-event
     (lambda (event) (setq unrelated event))
     ;; This is the pinned upstream parser's default array representation.
     (json-parse-string "{\"event\":\"layouts\",\"layouts\":[\"us\",\"ru\"],\"current\":1}"
                        :object-type 'alist :false-object nil))
    (should (equal sz/ewm-status-layout "ru"))
    (sz/ewm-status--handle-event
      (lambda (event) (setq unrelated event)) '((event . "bell") (id . 9)))
    (should (equal unrelated '((event . "bell") (id . 9))))
    (should (equal sz/ewm-status-layout "ru"))
    (sz/ewm-status--handle-event
     (lambda (_event) nil) '((event . "layout-switched") (layout . "us") (index . 0)))
    (should (equal sz/ewm-status-layout "us"))))

(ert-deftest sz/ewm-status-battery-hides-at-100-regardless-of-state ()
  (let ((battery-mode-line-format " %p%% battery")
        (battery-mode-line-limit 101)
        (battery-update-functions '(sz/ewm-status--battery-update))
        battery-mode-line-string)
    (dolist (case '(("Full" "100" nil)
                    ("Charging" "100.0" nil)
                    ("Charging" "95.1" t)
                    ("Charging" "95" t)
                    ("Charging" "94.9" t)
                    ("Discharging" "100.0" nil)
                    ("Discharging" "99.9" t)
                    ("Discharging" "95.1" t)
                    ("Discharging" "12" t)
                    ("Unknown" "100" nil)
                    ("Full" "99" t)
                    ("Charging" "101" nil)
                    ("Charging" "N/A" t)))
      (ert-info ((format "%S" case))
        (let ((battery-status-function
               (lambda () `((?B . ,(nth 0 case)) (?p . ,(nth 1 case))))))
          (battery-update))
        (if (nth 2 case)
            (should (equal battery-mode-line-string (format " %s%% battery" (nth 1 case))))
          (should-not battery-mode-line-string))))))

(ert-deftest sz/ewm-status-start-is-idempotent-and-stop-cleans-registrations ()
  (let ((sz/ewm-status-active nil) (sz/ewm-status--dbus-objects nil)
        (sz/ewm-status--dbus-provider-objects nil)
        starts unregisters)
    (cl-letf (((symbol-function 'display-time-mode) (lambda (&rest _) nil))
              ((symbol-function 'display-battery-mode) (lambda (&rest _) nil))
              ((symbol-function 'run-at-time) (lambda (&rest _) 'timer))
              ((symbol-function 'run-with-idle-timer) (lambda (&rest _) 'timer))
              ((symbol-function 'sz/ewm-status--timeblock-refresh) (lambda () (push 'timeblock starts)))
              ((symbol-function 'sz/ewm-status--audio-refresh) (lambda () (push 'audio starts)))
              ((symbol-function 'sz/ewm-status--dbus-refresh) (lambda () (push 'dbus starts)))
              ((symbol-function 'sz/ewm-status--register-dbus)
               (lambda () (setq sz/ewm-status--dbus-objects '(one two))))
              ((symbol-function 'dbus-unregister-object) (lambda (object) (push object unregisters))))
      (sz/ewm-status-start)
      (sz/ewm-status-start)
      (should (advice-member-p #'sz/ewm-status--handle-event 'ewm--handle-event))
      (should (advice-member-p #'sz/ewm-status--system-batteries
                              'battery--find-linux-sysfs-batteries))
      (should (equal (sort starts (lambda (a b) (string< (symbol-name a) (symbol-name b))))
                     '(audio dbus timeblock)))
      (sz/ewm-status-stop)
      (should-not sz/ewm-status-active)
      (should-not (advice-member-p #'sz/ewm-status--handle-event 'ewm--handle-event))
      (should-not (advice-member-p #'sz/ewm-status--system-batteries
                                  'battery--find-linux-sysfs-batteries))
      (should (equal (sort unregisters (lambda (a b) (string< (symbol-name a) (symbol-name b))))
                     '(one two))))))

(ert-deftest sz/ewm-status-sysfs-excludes-peripheral-battery-state ()
  ;; Exercise the real sysfs aggregator: laptop Full + keyboard Discharging
  ;; must not become a fictitious 100%-Discharging laptop.
  (let* ((root (make-temp-file "ewm-batteries-" t))
         (laptop (expand-file-name "BAT1" root))
         (keyboard (expand-file-name "keyboard" root))
         (battery-update-functions '(sz/ewm-status--battery-update))
         (battery-status-function #'battery-linux-sysfs)
         (battery-mode-line-limit 101)
         (battery-mode-line-format " %p%% battery")
         battery-mode-line-string)
    (unwind-protect
        (progn
          (dolist (dir (list laptop keyboard))
            (make-directory dir)
            (with-temp-file (expand-file-name "capacity" dir) (insert "100\n")))
          (with-temp-file (expand-file-name "scope" keyboard) (insert "Device\n"))
          (with-temp-file (expand-file-name "uevent" keyboard)
            (insert "POWER_SUPPLY_PRESENT=1\nPOWER_SUPPLY_STATUS=Discharging\n"))
          (advice-add 'battery--find-linux-sysfs-batteries :filter-return
                      #'sz/ewm-status--system-batteries)
          (cl-letf (((symbol-function 'battery--files) (lambda (_) (list laptop keyboard))))
            (dolist (state '("Full" "Charging" "Discharging"))
              (with-temp-file (expand-file-name "uevent" laptop)
                (insert (format "POWER_SUPPLY_PRESENT=1\nPOWER_SUPPLY_STATUS=%s\nPOWER_SUPPLY_ENERGY_FULL=100\nPOWER_SUPPLY_ENERGY_NOW=100\n" state)))
              (should (equal (battery--find-linux-sysfs-batteries) (list laptop)))
              (should (equal (cdr (assq ?B (battery-linux-sysfs))) state))
              (battery-update)
              (should-not battery-mode-line-string))))
      (advice-remove 'battery--find-linux-sysfs-batteries #'sz/ewm-status--system-batteries)
      (delete-directory root t))))

(ert-deftest sz/ewm-status-dbus-properties-decodes-real-variants-and-stale-snapshots ()
  (let ((sz/ewm-status-active t) (sz/ewm-status--dbus-generation 7)
        (token (list nil)) callback published)
    (setq sz/ewm-status--power-inflight token)
    (cl-letf (((symbol-function 'dbus-call-method-asynchronously)
               (lambda (&rest arguments) (setq callback (nth 5 arguments)))))
      (sz/ewm-status--dbus-get "service" "/path" "iface" "Property" 7 token
                                 (lambda (value) (setq published value))
                                 (lambda () (setq published 'failure)))
      (setq sz/ewm-status--dbus-generation 8)
      (funcall callback '("stale"))
      (should-not published))))

(ert-deftest sz/ewm-status-dbus-properties-preserves-false-and-array-variants ()
  (let ((sz/ewm-status-active t) (sz/ewm-status--dbus-generation 1)
        (token (list nil)) callbacks values)
    (setq sz/ewm-status--nm-inflight token)
    (cl-letf (((symbol-function 'dbus-call-method-asynchronously)
               (lambda (&rest arguments) (push (nth 5 arguments) callbacks))))
      (sz/ewm-status--dbus-get "service" "/path" "iface" "False" 1 token
                                 (lambda (value) (push value values)) #'ignore)
      (sz/ewm-status--dbus-get "service" "/path" "iface" "Array" 1 token
                                 (lambda (value) (push value values)) #'ignore)
      (funcall (car callbacks) '(("/one" "/two")))
      (funcall (cadr callbacks) '(nil))
      (should (equal values '(nil ("/one" "/two")))))))

(ert-deftest sz/ewm-status-nm-settings-uses-the-profile-id-not-an-interface-name ()
  (let ((sz/ewm-status-active t)
        (sz/ewm-status--dbus-generation 3)
        callback id failed)
    (cl-letf (((symbol-function 'dbus-call-method-asynchronously)
               (lambda (&rest arguments) (setq callback (nth 5 arguments)))))
      (let ((token (list nil)))
        (setq sz/ewm-status--nm-inflight token)
        (sz/ewm-status--nm-get-settings
         3 token "/org/freedesktop/NetworkManager/Settings/42"
         (lambda (value) (setq id value))
         (lambda () (setq failed t)))
        (funcall callback '(("connection" (("id" ("work-vpn")))))))
      (should (equal id "work-vpn"))
      (should-not failed))))

(ert-deftest sz/ewm-status-timeout-retires-a-late-provider-reply ()
  (let ((sz/ewm-status-active t) (sz/ewm-status--dbus-generation 1)
        (sz/ewm-status-power-saver "old") callback timeout)
    (cl-letf (((symbol-function 'dbus-call-method-asynchronously)
               (lambda (&rest arguments) (setq callback (nth 5 arguments))))
              ((symbol-function 'run-at-time)
               (lambda (&rest arguments) (setq timeout (nth 2 arguments)) 'timer)))
      (sz/ewm-status--power-refresh)
      (funcall timeout)
      (funcall callback '("power-saver"))
      (should (equal sz/ewm-status-power-saver "")))))

(ert-deftest sz/ewm-status-owner-replacement-rebinds-only-that-provider ()
  (let ((sz/ewm-status-active t) (sz/ewm-status--dbus-generation 1)
        (nm-token (list nil)) (power-token (list nil)) registrations removed)
    (setq sz/ewm-status--nm-inflight nm-token
          sz/ewm-status--power-inflight power-token
          sz/ewm-status--dbus-objects '(nm-watch power-watch)
          sz/ewm-status--dbus-provider-objects `((,sz/ewm-status--nm . (old-nm))))
    (cl-letf (((symbol-function 'dbus-register-signal)
               (lambda (&rest arguments) (push arguments registrations) 'new-nm))
              ((symbol-function 'dbus-unregister-object)
               (lambda (object) (push object removed)))
              ((symbol-function 'run-at-time) (lambda (&rest _) 'timer)))
      (sz/ewm-status--dbus-name-owner sz/ewm-status--nm ":old" ":new")
      (should (equal removed '(old-nm)))
      (should (= (length registrations) 3))
      (should-not sz/ewm-status--nm-inflight)
      (should (eq sz/ewm-status--power-inflight power-token))
      (should (equal sz/ewm-status--dbus-objects '(nm-watch power-watch))))))

(ert-deftest sz/ewm-status-provider-loss-clears-nm-and-defers-recovery ()
  (let ((sz/ewm-status-active t)
        (sz/ewm-status--dbus-generation 2)
        (sz/ewm-status-network "old")
        (sz/ewm-status-wireguard "work-vpn")
        (sz/ewm-status--nm-inflight t)
        (sz/ewm-status--power-inflight t)
        scheduled)
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (&rest arguments) (setq scheduled arguments) 'timer)))
      (sz/ewm-status--dbus-name-owner sz/ewm-status--nm ":1.1" "")
      (should (equal sz/ewm-status-network "network?"))
      (should (equal sz/ewm-status-wireguard ""))
      (should (= sz/ewm-status--dbus-generation 2))
      (should sz/ewm-status--power-inflight)
      (should scheduled))))

(ert-deftest sz/ewm-status-registers-only-provider-and-profile-signals ()
  (let ((sz/ewm-status--dbus-objects nil) (sz/ewm-status--dbus-provider-objects nil) registrations)
    (cl-letf (((symbol-function 'dbus-register-signal)
                (lambda (&rest arguments)
                  (push arguments registrations)
                  (list :subscription (length registrations))))
              ((symbol-function 'dbus-get-name-owner)
               (lambda (_bus name) (concat ":owner-" name))))
      (sz/ewm-status--register-dbus)
      (should (= (length registrations) 6))
      (should-not (seq-find (lambda (registration)
                              (and (equal (nth 3 registration) sz/ewm-status--properties)
                                   (null (nth 1 registration))))
                            registrations)))))

(ert-deftest sz/ewm-status-start-keeps-registration-recovery-through-snapshots ()
  (let ((sz/ewm-status-active nil) (sz/ewm-status--dbus-objects nil)
        (sz/ewm-status--dbus-provider-objects nil)
        (sz/ewm-status--dbus-registration-retry nil)
        (registration-fails t) owner-watches recovery snapshots)
    (cl-letf (((symbol-function 'display-time-mode) (lambda (&rest _) nil))
              ((symbol-function 'display-battery-mode) (lambda (&rest _) nil))
              ((symbol-function 'sz/ewm-status--timeblock-refresh) #'ignore)
              ((symbol-function 'sz/ewm-status--audio-refresh) #'ignore)
              ((symbol-function 'sz/ewm-status--nm-refresh) (lambda () (push 'nm snapshots)))
              ((symbol-function 'sz/ewm-status--power-refresh) (lambda () (push 'power snapshots)))
              ((symbol-function 'run-at-time)
               (lambda (&rest arguments)
                 (let ((timer (list 'timer (nth 2 arguments))))
                   (when (= (nth 0 arguments) 1) (setq recovery timer))
                   timer)))
              ((symbol-function 'dbus-register-signal)
               (lambda (&rest arguments)
                 (if registration-fails
                     (progn (setq registration-fails nil) (error "offline"))
                   (when (equal (nth 3 arguments) "org.freedesktop.DBus")
                     (push arguments owner-watches))
                   arguments)))
              ((symbol-function 'dbus-get-name-owner) (lambda (&rest _) ":owner")))
      (sz/ewm-status-start)
      (should (equal snapshots '(power nm)))
      (should (eq sz/ewm-status--dbus-registration-retry recovery))
      (funcall (cadr recovery))
      (should (= (length owner-watches) 2))
      (should-not sz/ewm-status--dbus-registration-retry)
      (sz/ewm-status-stop))))

(ert-deftest sz/ewm-status-stop-cancels-snapshot-and-registration-retries ()
  (let ((sz/ewm-status-active t)
        (sz/ewm-status--dbus-retry 'snapshot-retry)
        (sz/ewm-status--dbus-registration-retry 'registration-retry)
        (sz/ewm-status--saved-time
         (list display-time-format display-time-interval display-time-mode))
        (sz/ewm-status--saved-battery
         (list battery-mode-line-format battery-mode-line-limit display-battery-mode))
        cancelled)
    (cl-letf (((symbol-function 'sz/ewm-status--cancel) (lambda (timer) (push timer cancelled)))
              ((symbol-function 'display-time-mode) (lambda (&rest _) nil))
              ((symbol-function 'display-battery-mode) (lambda (&rest _) nil)))
      (sz/ewm-status-stop)
      (should (memq 'snapshot-retry cancelled))
      (should (memq 'registration-retry cancelled)))))

(ert-deftest sz/ewm-status-agenda-edits-debounce-without-parsing ()
  (let ((sz/ewm-status-active t) (invalidations 0))
    (with-temp-buffer
      (setq buffer-file-name "/tmp/agenda.org")
      (cl-letf (((symbol-function 'org-agenda-files) (lambda () '("/tmp/agenda.org")))
                ((symbol-function 'sz/ewm-status-timeblock-invalidate)
                 (lambda (&rest _) (cl-incf invalidations))))
        (sz/ewm-status--agenda-change)
        (should (= invalidations 1))))))

;;; sz-ewm-status-test.el ends here
