;;; sz-ewm-mode-line-test.el --- ERT checks for EWM mode-line placement -*- lexical-binding: t -*-

(require 'ert)

(defconst sz/ewm-mode-line-test-directory
  (expand-file-name ".." (file-name-directory load-file-name)))

;; The collector owns these variables.  Declaring them here models both its
;; loaded contract and the mode line's unbound-at-startup guard.
(defvar ewm-mode nil)
(defvar sz/ewm-status-active nil)
(defvar sz/ewm-status-timeblock nil)
(defvar sz/ewm-status-audio nil)
(defvar sz/ewm-status-network nil)
(defvar sz/ewm-status-wireguard nil)
(defvar sz/ewm-status-layout nil)
(defvar sz/ewm-status-power-saver nil)

(load (expand-file-name "lisp/sz-mode-line.el" sz/ewm-mode-line-test-directory)
      nil 'nomessage t)

(ert-deftest sz/ewm-mode-line-indexes-are-compact-and-one-based ()
  (should (equal (sz/ewm-mode-line--index "W" 'two '(one two three)) "W 2/3"))
  (should (equal (sz/ewm-mode-line--index "T" 'only '(only)) "T 1/1"))
  (should-not (sz/ewm-mode-line--index "W" 'missing '(one two))))

(ert-deftest sz/ewm-mode-line-reorders-an-existing-clock-once ()
  (let ((ewm-mode t)
        (global-mode-string '(org-mode-line-string display-time-string
                                                   display-battery-string)))
    (sz/ewm-mode-line-keep-clock-last)
    (should (equal global-mode-string
                   '(org-mode-line-string display-battery-string display-time-string)))))

(ert-deftest sz/ewm-mode-line-narrow-global-keeps-battery-before-org-clock ()
  (let ((global-mode-string '(org-mode-line-string display-battery-string
                                                   display-time-string)))
    (cl-letf (((symbol-function 'sz/ewm-mode-line--format)
               (lambda (construct)
                  (cond ((memq 'org-mode-line-string construct)
                         "Very long clocked Org heading")
                        ((memq 'display-battery-string construct) "12% battery")
                        ((memq 'display-time-string construct) "14:42")))))
      (let ((text (sz/ewm-mode-line--global-context 96)))
        (should (string-match-p "12% battery" text))
        (should (string-match-p "Very" text))
        (should (< (string-match "Very" text) (string-match "14:42" text)))
        (should (get-text-property (string-match "Very" text) 'help-echo text))))))

(ert-deftest sz/ewm-mode-line-non-ewm-keeps-mode-line-misc-info-unchanged ()
  (let ((ewm-mode nil)
        (global-mode-string (list (make-string 200 ?x)))
        (mode-line-misc-info '("before [" global-mode-string "] after")))
    (cl-letf (((symbol-function 'sz/ewm-mode-line--window-width) (lambda () 10))
              ((symbol-function 'sz/ewm-mode-line--editor-context)
               (lambda () (error "ordinary mode line must not assemble editor context"))))
      (should (equal (sz/ewm-mode-line--right-context)
                     (format-mode-line mode-line-misc-info))))))

(ert-deftest sz/ewm-mode-line-normal-status-keeps-cached-wording ()
  (let ((sz/ewm-status-timeblock "Review → 15:00")
        (sz/ewm-status-audio "52% audio +MIC")
        (sz/ewm-status-network "network?")
        (sz/ewm-status-wireguard "alpha: work | zeta")
        (sz/ewm-status-layout "ru")
        (sz/ewm-status-power-saver "POWER SAVER"))
    (cl-letf (((symbol-function 'sz/ewm-mode-line--workspace) (lambda (_) "W 2/4"))
              ((symbol-function 'sz/ewm-mode-line--tile) (lambda (_) "T 1/2")))
      (should (equal (sz/ewm-mode-line--desktop-status 120 (selected-frame))
                     "W 2/4 · T 1/2 · Review → 15:00 · 52% audio +MIC · network? · alpha: work | zeta · ru · POWER SAVER")))))

(ert-deftest sz/ewm-mode-line-narrow-status-preserves-critical-state ()
  (let ((sz/ewm-status-timeblock "Проверка документации → 15:00")
        (sz/ewm-status-audio "52% audio +MIC")
        (sz/ewm-status-network "network?")
        (sz/ewm-status-wireguard "very-long-wireguard-profile")
        (sz/ewm-status-layout "ru")
        (sz/ewm-status-power-saver "POWER SAVER"))
    (cl-letf (((symbol-function 'sz/ewm-mode-line--workspace) (lambda (_) "W 2/4"))
              ((symbol-function 'sz/ewm-mode-line--tile) (lambda (_) "T 1/2")))
      (let ((text (sz/ewm-mode-line--desktop-status 70 (selected-frame))))
        (should (string-match-p "W 2/4" text))
        (should-not (string-match-p "T 1/2" text))
        (should-not (string-match-p "52% audio" text))
        (should (string-match-p "+MIC" text))
        (should (string-match-p "network?" text))
        (should (get-text-property (string-match "Проверка" text) 'help-echo text))
        (should (get-text-property (string-match "very-long" text) 'help-echo text))))))

(ert-deftest sz/ewm-mode-line-surface-hides-editor-fields-only ()
  (with-temp-buffer
    (setq major-mode 'fundamental-mode)
    (should-not (sz/ewm-mode-line--surface-p))
    (should (sz/ewm-mode-line--editor-context))
    (setq major-mode 'ewm-surface-mode
          ewm-surface-title "Процент 50% и длинный заголовок")
    (should (sz/ewm-mode-line--surface-p))
    (should-not (sz/ewm-mode-line--editor-context))
    (let ((title (sz/ewm-mode-line--truncate ewm-surface-title 12)))
      (should (string-match-p "50%" ewm-surface-title))
      (should (equal (get-text-property 0 'help-echo title) ewm-surface-title)))))

(ert-deftest sz/ewm-mode-line-surface-title-yields-to-right-status-budget ()
  (with-temp-buffer
    (setq major-mode 'ewm-surface-mode
          ewm-surface-title "A very long external application title")
    (cl-letf (((symbol-function 'sz/ewm-mode-line--window-width) (lambda () 30))
              ((symbol-function 'sz/ewm-mode-line--right-context)
               (lambda () "W 1/2 · MUTED · 12% battery")))
      (let ((title (sz/ewm-mode-line--identification)))
        (should (< (string-width title) (string-width ewm-surface-title)))
        (should (equal (get-text-property 0 'help-echo title) ewm-surface-title))))))

(ert-deftest sz/ewm-mode-line-right-context-bounds-wide-and-narrow-assemblies ()
  (let ((ewm-mode t)
        (sz/ewm-status-active t)
        (sz/ewm-status-timeblock "100% План: документация для очень длинного релиза → 15:00")
        (sz/ewm-status-audio "52% audio +MIC")
        (sz/ewm-status-network "network?")
        (sz/ewm-status-wireguard "WG-имя-профиля-with-a-very-long-unicode-name")
        (sz/ewm-status-layout "ru")
        (sz/ewm-status-power-saver "POWER SAVER")
        (global-mode-string '(org-mode-line-string display-battery-string display-time-string)))
    (dolist (width '(140 96 70))
      (let ((formats 0))
        (with-temp-buffer
          (setq major-mode 'ewm-surface-mode
                ewm-surface-title "A title that must not make the right status overflow")
          (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () t))
                    ((symbol-function 'sz/ewm-mode-line--window-width) (lambda () width))
                    ((symbol-function 'sz/ewm-mode-line--workspace) (lambda (_) "W 2/4"))
                    ((symbol-function 'sz/ewm-mode-line--tile) (lambda (_) "T 1/2"))
                    ((symbol-function 'sz/ewm-mode-line--format)
                     (lambda (construct)
                       (setq formats (1+ formats))
                       (cond ((memq 'org-mode-line-string construct)
                              "Org 100%: heading that is deliberately much longer than its budget")
                             ((memq 'display-battery-string construct) "12% battery")
                             ((memq 'display-time-string construct) "02 Jan 14:42")))))
            (let ((text (sz/ewm-mode-line--right-context)))
              (should (<= (string-width text) width))
              (should (= formats 3))
              (dolist (needle '("+MIC" "network?" "12% battery" "02 Jan 14:42"))
                (should (string-match-p needle text)))
              (when (< width 100)
                (should-not (string-match-p "T 1/2" text))
                (should-not (string-match-p "52% audio" text)))
              )))))))

(ert-deftest sz/ewm-mode-line-right-context-tiny-window-is-explicit-best-effort ()
  (let ((ewm-mode t)
        (sz/ewm-status-active t)
        (sz/ewm-status-audio "52% audio +MIC")
        (sz/ewm-status-network "network?")
        (sz/ewm-status-layout "ru")
        (sz/ewm-status-power-saver "POWER SAVER")
        (global-mode-string '(display-battery-string display-time-string)))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () t))
              ((symbol-function 'sz/ewm-mode-line--window-width) (lambda () 10))
              ((symbol-function 'sz/ewm-mode-line--workspace) (lambda (_) "W 2/4"))
              ((symbol-function 'sz/ewm-mode-line--format)
               (lambda (_) "12% battery 02 Jan 14:42")))
      (let ((text (sz/ewm-mode-line--right-context)))
        (should (> (string-width text) 10))
        (should (string-match-p "+MIC" text))
        (should (string-match-p "network?" text))
        (should (string-match-p "12% battery" text))))))

(ert-deftest sz/ewm-mode-line-right-context-handles-ordinary-and-surface-tiles ()
  (let ((selected t)
        (sz/ewm-status-active t))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () selected))
              ((symbol-function 'sz/ewm-mode-line--window-width) (lambda () 120))
              ((symbol-function 'sz/ewm-mode-line--editor-context) (lambda () "EDITOR"))
              ((symbol-function 'sz/ewm-mode-line--global-context)
               (lambda (&optional _ components) (if components '("GLOBAL" nil nil) "GLOBAL")))
              ((symbol-function 'sz/ewm-mode-line--format)
               (lambda (construct) (if (eq construct 'mode-line-misc-info) "MISC" "")))
              ((symbol-function 'sz/ewm-mode-line--desktop-status) (lambda (&rest _) "DESKTOP")))
      (let ((ewm-mode nil))
        (should (equal (sz/ewm-mode-line--right-context) "MISC")))
      (let ((ewm-mode t))
        (setq selected nil)
        (should (equal (sz/ewm-mode-line--right-context) "EDITOR"))
        (setq selected t)
        (cl-letf (((symbol-function 'sz/ewm-mode-line--editor-context) (lambda () nil)))
          (should (equal (sz/ewm-mode-line--right-context) "DESKTOP GLOBAL")))))))

(ert-deftest sz/ewm-mode-line-right-context-puts-org-before-final-clock ()
  (let ((ewm-mode t)
        (sz/ewm-status-active t)
        (global-mode-string '(org-mode-line-string display-battery-string display-time-string)))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () t))
              ((symbol-function 'sz/ewm-mode-line--window-width) (lambda () 120))
              ((symbol-function 'sz/ewm-mode-line--editor-context) (lambda () "EDITOR"))
              ((symbol-function 'sz/ewm-mode-line--desktop-status) (lambda (&rest _) "DESKTOP"))
              ((symbol-function 'sz/ewm-mode-line--format)
               (lambda (construct)
                 (cond ((memq 'org-mode-line-string construct) "ORG")
                       ((memq 'display-battery-string construct) "BATTERY")
                       ((memq 'display-time-string construct) "CLOCK")))))
      (let ((text (sz/ewm-mode-line--right-context)))
        (should (equal text "EDITOR DESKTOP BATTERY ORG CLOCK"))
        (should (< (string-match "ORG" text) (string-match "CLOCK" text)))))))

(ert-deftest sz/ewm-mode-line-wide-tile-keeps-layout-and-power-with-small-status-budget ()
  (let ((ewm-mode t)
        (sz/ewm-status-active t)
        (sz/ewm-status-timeblock "Agenda")
        (sz/ewm-status-layout "ru")
        (sz/ewm-status-power-saver "POWER SAVER")
        (global-mode-string '(display-battery-string display-time-string)))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () t))
              ((symbol-function 'sz/ewm-mode-line--window-width) (lambda () 140))
              ((symbol-function 'sz/ewm-mode-line--workspace) (lambda (_) "W 2/4"))
              ((symbol-function 'sz/ewm-mode-line--format)
               (lambda (construct)
                 (if (memq 'display-battery-string construct) "BATTERY" "CLOCK"))))
      (let ((text (sz/ewm-mode-line--right-context)))
        (should (string-match-p "ru" text))
        (should (string-match-p "POWER SAVER" text))))))

(ert-deftest sz/ewm-mode-line-desktop-is-selected-window-only ()
  (let ((ewm-mode t)
        (sz/ewm-status-active t))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () t)))
      (should (sz/ewm-mode-line--desktop-p)))
    (cl-letf (((symbol-function 'mode-line-window-selected-p) (lambda () nil)))
      (should-not (sz/ewm-mode-line--desktop-p)))
    (let ((sz/ewm-status-active nil))
      (should-not (sz/ewm-mode-line--desktop-p)))))

;;; sz-ewm-mode-line-test.el ends here
