;;; sz-ewm-test.el --- ERT checks for the local EWM profile -*- lexical-binding: t -*-

(require 'ert)
(require 'cl-lib)

(defconst sz/ewm-test-emacs-directory
  (file-name-as-directory
   (expand-file-name ".." (file-name-directory load-file-name))))
(defconst sz/ewm-test-upstream-directory
  (or (getenv "EWM_TEST_SOURCE")
      (error "Set EWM_TEST_SOURCE to the pinned EWM lisp directory")))

(add-to-list 'load-path sz/ewm-test-upstream-directory)
(add-to-list 'load-path (expand-file-name "lisp/ewm" sz/ewm-test-emacs-directory))

;; Mocks only the native module boundary; all tested policy and event code is
;; loaded from the pinned upstream Lisp source selected by EWM_TEST_SOURCE.
(dolist (stub '((ewm-intercept-keys-module (&rest _))
                (ewm-configure-input-module (&rest _))
                (ewm-configure-output-module (&rest _))
                (ewm-keyboard-capture-begin-module (&rest _) 1)
                (ewm-keyboard-capture-end-module (&rest _) t)
                (ewm-keyboard-redirect-capture-clear-module (&rest _))
                (ewm-set-drag-source (&rest _))
                (ewm-get-focused-id (&rest _))
                (ewm-get-focused-frame-id (&rest _))
                (ewm-get-pointer-location (&rest _) '(0 . 0))
                (ewm-output-layout-module (&rest _))
                (ewm-floating-layout-module (&rest _))
                (ewm-close-module (&rest _))
                (ewm-warp-pointer-module (&rest _))
                (ewm-get-debug-state-module (&rest _))
                (ewm-debug-mode-module (&rest _))
                (ewm-prepare-frame-module (&rest _))
                (ewm-prepare-floating-frame-module (&rest _))
                (ewm-prepare-frame-close-module (&rest _))
                (ewm-move-floating-frame-module (&rest _))
                (ewm-resize-floating-frame-module (&rest _))
                (ewm-workspace-rename-module (&rest _))
                (ewm-workspace-mark-urgent-module (&rest _))
                (ewm-toggle-fullscreen-module (&rest _))
                (ewm-get-active-outputs (&rest _))
                (ewm-get-output-origin (&rest _) '(0 . 0))
                (ewm-get-frame-origin (&rest _) '(0 . 0))
                (ewm-entry-under-floating-center-module (&rest _))
                (ewm-configure-cursor-module (&rest _))
                (ewm-configure-cursor-hide-module (&rest _))
                (ewm-start (&rest _) t)
                (ewm-list-xdg-apps (&rest _))
                (ewm-set-focus-follows-mouse (&rest _))
                (ewm-set-unfocused-alpha (&rest _))
                (ewm-set-animations-enabled (&rest _))
                (ewm-notify-initialized-module (&rest _))
                (ewm-focus-output-direction-module (&rest _))
                (ewm-init-event-channel (&rest _))
                (ewm-set-selection-module (&rest _))
                (ewm-gtk-set-style (&rest _))
                (ewm-im-commit-module (&rest _))
                (ewm-text-input-intercept-module (&rest _))))
  (unless (fboundp (car stub))
    (eval `(defun ,(car stub) ,(cadr stub) ,@(cddr stub)))))
(provide 'ewm-core)

(require 'ewm)
(load (expand-file-name "lisp/ewm/sz-ewm.el" sz/ewm-test-emacs-directory) nil 'nomessage t)
(load (expand-file-name "lisp/functions/sz-org-capture-frame.el" sz/ewm-test-emacs-directory)
      nil 'nomessage t)

(ert-deftest sz/ewm-profile-keeps-editor-prefixes-out-of-external-apps ()
  (let ((ewm--module-mode nil)
        (sz/ewm-output-selector nil)
        sent)
    (sz/ewm-apply-profile)
    (should (eq (lookup-key ewm-mode-map (kbd "s-m")) #'ewm-frame-new))
    (should (eq (lookup-key ewm-mode-map (kbd "M-s-,")) #'ewm-frame-new))
    (should (eq (lookup-key ewm-mode-map (kbd "s-w")) #'ewm-frame-close))
    (should (eq (lookup-key ewm-mode-map (kbd "M-s-l")) #'sz/ewm-split-right))
    (should (eq (lookup-key ewm-mode-map (kbd "s-;")) #'org-capture))
    (should (eq (lookup-key ewm-mode-map (kbd "S-s-e")) #'sz/ewm-logout))
    (should-not ewm-surface-emulate-keys)
    (should (eq confirm-kill-emacs #'yes-or-no-p))
    (cl-letf (((symbol-function 'ewm-intercept-keys-module)
               (lambda (specs) (setq sent specs))))
      (ewm--send-intercept-keys))
    (dolist (description '("C-x" "C-u" "C-h" "M-x"))
      (should-not (seq-find (lambda (spec)
                              (equal (plist-get spec :description) description))
                            sent)))
    (dolist (description '("s-<escape>" "S-s-e" "s-<f8>" "S-s-<f8>" "s-;"
                           "<Print>" "C-<Print>" "S-<Print>"
                           "<MonBrightnessUp>" "<MonBrightnessDown>"
                           "<AudioPlay>" "<AudioRaiseVolume>"
                           "<AudioLowerVolume>" "<AudioMicMute>"
                           "<HomePage>" "<AudioMute>" "S-s-m"))
      (let ((spec (seq-find (lambda (candidate)
                              (equal (plist-get candidate :description) description))
                            sent)))
        (should spec)
        (should (eq (plist-get spec :fullscreen) t))))
    (dolist (spec (append sent nil))
      (should-not (plist-member spec :translate)))))

(ert-deftest sz/ewm-refresh-survives-upstream-output-reapply ()
  (let ((sz/ewm-output-selector "Live output selector")
        (sz/ewm-output-refresh 240)
        (ewm--module-mode t)
        applied)
    (cl-letf (((symbol-function 'start-process) (lambda (&rest _) nil))
              ((symbol-function 'ewm-configure-output-module)
               (lambda (&rest args) (push args applied))))
      (sz/ewm-power-saver)
      (should (= sz/ewm-output-refresh 60))
      (should (equal (plist-get (cdr (car ewm-output-config)) :refresh) 60))
      (setq applied nil)
      ;; Actual upstream topology completion calls `ewm--apply-output-config'.
      (ewm--handle-outputs-complete)
      (should applied))))

(ert-deftest sz/ewm-capture-uses-org-directly-while-ewm-runs ()
  (let (captured)
    (cl-letf (((symbol-function 'ewm-running) (lambda () t))
              ((symbol-function 'org-capture) (lambda () (setq captured t))))
      (sz/org-capture-in-frame)
      (should captured))))

(ert-deftest sz/ewm-logout-delegates-to-emacs-save-confirmation ()
  (let (called)
    (cl-letf (((symbol-function 'call-interactively)
               (lambda (command &rest _) (setq called command))))
      (sz/ewm-logout)
      (should (eq called #'save-buffers-kill-emacs)))))

(ert-deftest sz/ewm-split-selects-the-new-native-tile ()
  (let ((new-window 'new-window)
        selected)
    (cl-letf (((symbol-function 'split-window-right) (lambda () new-window))
              ((symbol-function 'select-window) (lambda (window) (setq selected window))))
      (sz/ewm-split-right)
      (should (eq selected new-window)))))

(ert-deftest sz/ewm-screenshots-keep-the-existing-grim-default-directory ()
  (let ((process-environment (cons "GRIM_DEFAULT_DIR=/tmp/Pictures/Screenshots"
                                   process-environment))
        command inherited-directory)
    (cl-letf (((symbol-function 'start-process-shell-command)
               (lambda (_name _buffer shell-command)
                 (setq command shell-command
                       inherited-directory (getenv "GRIM_DEFAULT_DIR")))))
      (sz/ewm-screenshot-region)
      (should (equal command "grim -g \"$(slurp)\""))
      (should (equal inherited-directory "/tmp/Pictures/Screenshots")))))

;;; sz-ewm-test.el ends here
