#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."
scanner=github.com/MatthiasKunnen/go-wayland/cmd/go-wayland-scanner
package_dir=internal/riverxkb

printf '%s  %s\n' \
  122ada3beb5d4cb5984fe122f7886c2a048e261852a50e8d2e6926e3958bb98b "$package_dir/protocol/river-input-management-v1.xml" \
  bb859cec256e2b1e85a5f516cc94179409fb9adf94665d2217ba5636048439b3 "$package_dir/protocol/river-xkb-config-v1.xml" |
  sha256sum --check --strict

go run "$scanner" -pkg riverxkb -prefix river -suffix v1 \
  -i "$package_dir/protocol/river-input-management-v1.xml" \
  -o "$package_dir/river_input_management_v1.go"
go run "$scanner" -pkg riverxkb -prefix river -suffix v1 \
  -i "$package_dir/protocol/river-xkb-config-v1.xml" \
  -o "$package_dir/river_xkb_config_v1.go"

python3 - "$package_dir" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1])
revision = "github.com/MatthiasKunnen/go-wayland@412de804cb23568a899c4ad2f6b8408b38184e9c"
river = "river v0.4.8 (c4b5f706314555f4846e25b8d3635631387b3fdd)"
files = {
    "river_input_management_v1.go": (
        "protocol/river-input-management-v1.xml",
        "e.Id = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*InputDevice)",
        "e.Id = newInputDevice(i.Context(), client.Uint32(data[l:l+4]))",
    ),
    "river_xkb_config_v1.go": (
        "protocol/river-xkb-config-v1.xml",
        "e.Id = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*XkbKeyboard)",
        "e.Id = newXkbKeyboard(i.Context(), client.Uint32(data[l:l+4]))",
    ),
}
for name, (xml, old, new) in files.items():
    path = root / name
    text = path.read_text()
    marker = "// Generated by go-wayland-scanner\n"
    header = marker + f"// Generator revision: {revision}\n// River XML provenance: {river}, {xml}\n"
    if text.count(marker) != 1 or text.count(old) != 1:
        raise SystemExit(f"unexpected generated shape in {path}")
    path.write_text(text.replace(marker, header, 1).replace(old, new, 1))
PY

gofmt -w "$package_dir/river_input_management_v1.go" "$package_dir/river_xkb_config_v1.go"
