// Generated by go-wayland-scanner
// Generator revision: github.com/MatthiasKunnen/go-wayland@412de804cb23568a899c4ad2f6b8408b38184e9c
// River XML provenance: river v0.4.8 (c4b5f706314555f4846e25b8d3635631387b3fdd), protocol/river-xkb-config-v1.xml
// https://github.com/MatthiasKunnen/go-wayland/cmd/go-wayland-scanner
// XML file : internal/riverxkb/protocol/river-xkb-config-v1.xml
//
// river_xkb_config_v1 Protocol Copyright:
//
// SPDX-FileCopyrightText: © 2026 Isaac Freund
// SPDX-License-Identifier: MIT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

package riverxkb

import (
	"github.com/MatthiasKunnen/go-wayland/wayland/client"
	"golang.org/x/sys/unix"
)

// XkbConfigInterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const XkbConfigInterfaceName = "river_xkb_config_v1"

// XkbConfig : xkb config global interface
//
// Global interface for configuring xkb devices.
//
// This global should only be advertised if river_input_manager_v1 is
// advertised as well.
type XkbConfig struct {
	client.BaseProxy
	finishedHandler    XkbConfigFinishedHandlerFunc
	xkbKeyboardHandler XkbConfigXkbKeyboardHandlerFunc
}

// NewXkbConfig : xkb config global interface
//
// Global interface for configuring xkb devices.
//
// This global should only be advertised if river_input_manager_v1 is
// advertised as well.
func NewXkbConfig(ctx *client.Context) *XkbConfig {
	riverXkbConfigV1 := &XkbConfig{}
	ctx.Register(riverXkbConfigV1)
	return riverXkbConfigV1
}

// Stop : stop sending events
//
// This request indicates that the client no longer wishes to receive
// events on this object.
//
// The Wayland protocol is asynchronous, which means the server may send
// further events until the stop request is processed. The client must wait
// for a river_xkb_config_v1.finished event before destroying this object.
func (i *XkbConfig) Stop() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy the river_xkb_config_v1 object
//
// This request should be called after the finished event has been received
// to complete destruction of the object.
//
// It is a protocol error to make this request before the finished event
// has been received.
//
// If a client wishes to destroy this object it should send a
// river_xkb_config_v1.stop request and wait for a
// river_xkb_config_v1.finished event. Once the finished event is received
// it is safe to destroy this object and any other objects created through
// this interface.
func (i *XkbConfig) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CreateKeymap : create a keymap object
//
// The server must be able to mmap the fd with MAP_PRIVATE.
// The server will fstat the fd to obtain the size of the keymap.
// The client must not modify the contents of the fd after making this request.
// The client should seal the fd with fcntl.
func (i *XkbConfig) CreateKeymap(fd int, format uint32) (*XkbKeymap, error) {
	id := NewXkbKeymap(i.Context())
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(format))
	l += 4
	oob := unix.UnixRights(int(fd))
	err := i.Context().WriteMsg(_reqBuf[:], oob)
	return id, err
}

type XkbConfigError uint32

// XkbConfigError :
const (
	XkbConfigErrorInvalidDestroy XkbConfigError = 0
	XkbConfigErrorInvalidFormat  XkbConfigError = 1
)

func (e XkbConfigError) Name() string {
	switch e {
	case XkbConfigErrorInvalidDestroy:
		return "invalid_destroy"
	case XkbConfigErrorInvalidFormat:
		return "invalid_format"
	default:
		return ""
	}
}

func (e XkbConfigError) Value() string {
	switch e {
	case XkbConfigErrorInvalidDestroy:
		return "0"
	case XkbConfigErrorInvalidFormat:
		return "1"
	default:
		return ""
	}
}

func (e XkbConfigError) String() string {
	return e.Name() + "=" + e.Value()
}

type XkbConfigKeymapFormat uint32

// XkbConfigKeymapFormat :
const (
	// XkbConfigKeymapFormatText : XKB_KEYMAP_FORMAT_TEXT_V1
	XkbConfigKeymapFormatText XkbConfigKeymapFormat = 1
	// XkbConfigKeymapFormatTextV2 : XKB_KEYMAP_FORMAT_TEXT_V2
	XkbConfigKeymapFormatTextV2 XkbConfigKeymapFormat = 2
)

func (e XkbConfigKeymapFormat) Name() string {
	switch e {
	case XkbConfigKeymapFormatText:
		return "text_v1"
	case XkbConfigKeymapFormatTextV2:
		return "text_v2"
	default:
		return ""
	}
}

func (e XkbConfigKeymapFormat) Value() string {
	switch e {
	case XkbConfigKeymapFormatText:
		return "1"
	case XkbConfigKeymapFormatTextV2:
		return "2"
	default:
		return ""
	}
}

func (e XkbConfigKeymapFormat) String() string {
	return e.Name() + "=" + e.Value()
}

// XkbConfigFinishedEvent : the server has finished with the object
//
// This event indicates that the server will send no further events on this
// object. The client should destroy the object. See
// river_xkb_config_v1.destroy for more information.
type XkbConfigFinishedEvent struct{}
type XkbConfigFinishedHandlerFunc func(XkbConfigFinishedEvent)

// SetFinishedHandler : sets handler for XkbConfigFinishedEvent
func (i *XkbConfig) SetFinishedHandler(f XkbConfigFinishedHandlerFunc) {
	i.finishedHandler = f
}

// XkbConfigXkbKeyboardEvent : new xkb keyboard
//
// A new xkbcommon keyboard has been created. Not every
// river_input_device_v1 is necessarily an xkbcommon keyboard as well.
type XkbConfigXkbKeyboardEvent struct {
	Id *XkbKeyboard
}
type XkbConfigXkbKeyboardHandlerFunc func(XkbConfigXkbKeyboardEvent)

// SetXkbKeyboardHandler : sets handler for XkbConfigXkbKeyboardEvent
func (i *XkbConfig) SetXkbKeyboardHandler(f XkbConfigXkbKeyboardHandlerFunc) {
	i.xkbKeyboardHandler = f
}

func (i *XkbConfig) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.finishedHandler == nil {
			return
		}
		var e XkbConfigFinishedEvent

		i.finishedHandler(e)
	case 1:
		if i.xkbKeyboardHandler == nil {
			return
		}
		var e XkbConfigXkbKeyboardEvent
		l := 0
		e.Id = newXkbKeyboard(i.Context(), client.Uint32(data[l:l+4]))
		l += 4

		i.xkbKeyboardHandler(e)
	}
}

// XkbKeymapInterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const XkbKeymapInterfaceName = "river_xkb_keymap_v1"

// XkbKeymap : xkbcommon keymap
//
// This object is the result of attempting to create an xkbcommon keymap.
type XkbKeymap struct {
	client.BaseProxy
	successHandler XkbKeymapSuccessHandlerFunc
	failureHandler XkbKeymapFailureHandlerFunc
}

// NewXkbKeymap : xkbcommon keymap
//
// This object is the result of attempting to create an xkbcommon keymap.
func NewXkbKeymap(ctx *client.Context) *XkbKeymap {
	riverXkbKeymapV1 := &XkbKeymap{}
	ctx.Register(riverXkbKeymapV1)
	return riverXkbKeymapV1
}

// Destroy : destroy the keymap object
//
// This request indicates that the client will no longer use the keymap
// object and that it may be safely destroyed.
func (i *XkbKeymap) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// XkbKeymapSuccessEvent : keymap creation succeeded
//
// The keymap object was successfully created and may be used with the
// river_xkb_keyboard_v1.set_keymap request.
type XkbKeymapSuccessEvent struct{}
type XkbKeymapSuccessHandlerFunc func(XkbKeymapSuccessEvent)

// SetSuccessHandler : sets handler for XkbKeymapSuccessEvent
func (i *XkbKeymap) SetSuccessHandler(f XkbKeymapSuccessHandlerFunc) {
	i.successHandler = f
}

// XkbKeymapFailureEvent : keymap creation failed
//
// The compositor failed to create a keymap from the given parameters.
//
// It is a protocol error to use this keymap object with
// river_xkb_keyboard_v1.set_keymap.
type XkbKeymapFailureEvent struct {
	ErrorMsg string
}
type XkbKeymapFailureHandlerFunc func(XkbKeymapFailureEvent)

// SetFailureHandler : sets handler for XkbKeymapFailureEvent
func (i *XkbKeymap) SetFailureHandler(f XkbKeymapFailureHandlerFunc) {
	i.failureHandler = f
}

func (i *XkbKeymap) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.successHandler == nil {
			return
		}
		var e XkbKeymapSuccessEvent

		i.successHandler(e)
	case 1:
		if i.failureHandler == nil {
			return
		}
		var e XkbKeymapFailureEvent
		l := 0
		errorMsgLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.ErrorMsg = client.String(data[l : l+errorMsgLen])
		l += errorMsgLen

		i.failureHandler(e)
	}
}

// XkbKeyboardInterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const XkbKeyboardInterfaceName = "river_xkb_keyboard_v1"

// XkbKeyboard : xkbcommon keyboard device
//
// This object represent a physical keyboard which has its configuration and
// state managed by xkbcommon.
type XkbKeyboard struct {
	client.BaseProxy
	removedHandler          XkbKeyboardRemovedHandlerFunc
	inputDeviceHandler      XkbKeyboardInputDeviceHandlerFunc
	layoutHandler           XkbKeyboardLayoutHandlerFunc
	capslockEnabledHandler  XkbKeyboardCapslockEnabledHandlerFunc
	capslockDisabledHandler XkbKeyboardCapslockDisabledHandlerFunc
	numlockEnabledHandler   XkbKeyboardNumlockEnabledHandlerFunc
	numlockDisabledHandler  XkbKeyboardNumlockDisabledHandlerFunc
	doneHandler             XkbKeyboardDoneHandlerFunc
}

// NewXkbKeyboard : xkbcommon keyboard device
//
// This object represent a physical keyboard which has its configuration and
// state managed by xkbcommon.
func NewXkbKeyboard(ctx *client.Context) *XkbKeyboard {
	riverXkbKeyboardV1 := &XkbKeyboard{}
	ctx.Register(riverXkbKeyboardV1)
	return riverXkbKeyboardV1
}

// Destroy : destroy the xkb keyboard object
//
// This request indicates that the client will no longer use the keyboard
// object and that it may be safely destroyed.
func (i *XkbKeyboard) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetKeymap : set the keymap
//
// Set the keymap for the keyboard.
//
// Setting a keymap will reset all layout/modifier state.
//
// It is a protocol error to pass a keymap object for which the
// river_xkb_keymap_v1.success event was not received.
func (i *XkbKeyboard) SetKeymap(keymap *XkbKeymap) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], keymap.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetLayoutByIndex : set the active layout by index
//
// Set the active layout for the keyboard's keymap. Has no effect if the
// layout index is out of bounds for the current keymap.
func (i *XkbKeyboard) SetLayoutByIndex(index int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(index))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetLayoutByName : set the active layout by name
//
// Set the active layout for the keyboard's keymap. Has no effect if there
// is no layout with the give name for the keyboard's keymap.
func (i *XkbKeyboard) SetLayoutByName(name string) error {
	const opcode = 3
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// CapslockEnable : enable capslock
//
// Enable capslock for the keyboard.
func (i *XkbKeyboard) CapslockEnable() error {
	const opcode = 4
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CapslockDisable : disable capslock
//
// Disable capslock for the keyboard.
func (i *XkbKeyboard) CapslockDisable() error {
	const opcode = 5
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// NumlockEnable : enable numlock
//
// Enable numlock for the keyboard.
func (i *XkbKeyboard) NumlockEnable() error {
	const opcode = 6
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// NumlockDisable : disable numlock
//
// Disable numlock for the keyboard.
func (i *XkbKeyboard) NumlockDisable() error {
	const opcode = 7
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type XkbKeyboardError uint32

// XkbKeyboardError :
const (
	XkbKeyboardErrorInvalidKeymap XkbKeyboardError = 0
)

func (e XkbKeyboardError) Name() string {
	switch e {
	case XkbKeyboardErrorInvalidKeymap:
		return "invalid_keymap"
	default:
		return ""
	}
}

func (e XkbKeyboardError) Value() string {
	switch e {
	case XkbKeyboardErrorInvalidKeymap:
		return "0"
	default:
		return ""
	}
}

func (e XkbKeyboardError) String() string {
	return e.Name() + "=" + e.Value()
}

// XkbKeyboardRemovedEvent : the xkb keyboard is removed
//
// This event indicates that the xkb keyboard has been removed.
//
// The server will send no further events on this object and ignore any
// request (other than river_xkb_keyboard_v1.destroy) made after this event
// is sent. The client should destroy this object with the
// river_xkb_keyboard_v1.destroy request to free up resources.
type XkbKeyboardRemovedEvent struct{}
type XkbKeyboardRemovedHandlerFunc func(XkbKeyboardRemovedEvent)

// SetRemovedHandler : sets handler for XkbKeyboardRemovedEvent
func (i *XkbKeyboard) SetRemovedHandler(f XkbKeyboardRemovedHandlerFunc) {
	i.removedHandler = f
}

// XkbKeyboardInputDeviceEvent : corresponding river input device
//
// The river_input_device_v1 corresponding to this xkb keyboard. This event
// will always be the first event sent on the river_xkb_keyboard_v1 object,
// and it will be sent exactly once.
type XkbKeyboardInputDeviceEvent struct {
	Device *InputDevice
}
type XkbKeyboardInputDeviceHandlerFunc func(XkbKeyboardInputDeviceEvent)

// SetInputDeviceHandler : sets handler for XkbKeyboardInputDeviceEvent
func (i *XkbKeyboard) SetInputDeviceHandler(f XkbKeyboardInputDeviceHandlerFunc) {
	i.inputDeviceHandler = f
}

// XkbKeyboardLayoutEvent : currently active layout
//
// The currently active layout index and name. The name arg may be null if
// the active layout does not have a name.
//
// This event is sent once when the river_xkb_keyboard_v1 is created and
// again whenever the layout changes.
type XkbKeyboardLayoutEvent struct {
	Index uint32
	Name  string
}
type XkbKeyboardLayoutHandlerFunc func(XkbKeyboardLayoutEvent)

// SetLayoutHandler : sets handler for XkbKeyboardLayoutEvent
func (i *XkbKeyboard) SetLayoutHandler(f XkbKeyboardLayoutHandlerFunc) {
	i.layoutHandler = f
}

// XkbKeyboardCapslockEnabledEvent : capslock is currently enabled
//
// Capslock is currently enabled for the keyboard.
//
// This event is sent once when the river_xkb_keyboard_v1 is created and
// again whenever the capslock state changes.
type XkbKeyboardCapslockEnabledEvent struct{}
type XkbKeyboardCapslockEnabledHandlerFunc func(XkbKeyboardCapslockEnabledEvent)

// SetCapslockEnabledHandler : sets handler for XkbKeyboardCapslockEnabledEvent
func (i *XkbKeyboard) SetCapslockEnabledHandler(f XkbKeyboardCapslockEnabledHandlerFunc) {
	i.capslockEnabledHandler = f
}

// XkbKeyboardCapslockDisabledEvent : capslock is currently disabled
//
// Capslock is currently disabled for the keyboard.
//
// This event is sent once when the river_xkb_keyboard_v1 is created and
// again whenever the capslock state changes.
type XkbKeyboardCapslockDisabledEvent struct{}
type XkbKeyboardCapslockDisabledHandlerFunc func(XkbKeyboardCapslockDisabledEvent)

// SetCapslockDisabledHandler : sets handler for XkbKeyboardCapslockDisabledEvent
func (i *XkbKeyboard) SetCapslockDisabledHandler(f XkbKeyboardCapslockDisabledHandlerFunc) {
	i.capslockDisabledHandler = f
}

// XkbKeyboardNumlockEnabledEvent : numlock is currently enabled
//
// Numlock is currently enabled for the keyboard.
//
// This event is sent once when the river_xkb_keyboard_v1 is created and
// again whenever the numlock state changes.
type XkbKeyboardNumlockEnabledEvent struct{}
type XkbKeyboardNumlockEnabledHandlerFunc func(XkbKeyboardNumlockEnabledEvent)

// SetNumlockEnabledHandler : sets handler for XkbKeyboardNumlockEnabledEvent
func (i *XkbKeyboard) SetNumlockEnabledHandler(f XkbKeyboardNumlockEnabledHandlerFunc) {
	i.numlockEnabledHandler = f
}

// XkbKeyboardNumlockDisabledEvent : numlock is currently disabled
//
// Numlock is currently disabled for the keyboard.
//
// This event is sent once when the river_xkb_keyboard_v1 is created and
// again whenever the numlock state changes.
type XkbKeyboardNumlockDisabledEvent struct{}
type XkbKeyboardNumlockDisabledHandlerFunc func(XkbKeyboardNumlockDisabledEvent)

// SetNumlockDisabledHandler : sets handler for XkbKeyboardNumlockDisabledEvent
func (i *XkbKeyboard) SetNumlockDisabledHandler(f XkbKeyboardNumlockDisabledHandlerFunc) {
	i.numlockDisabledHandler = f
}

// XkbKeyboardDoneEvent : all information has been sent
//
// This event is sent after all information about the keyboard has been
// sent.
//
// This allows changes to one or more river_xkb_keyboard_v1 properties to
// be seen as atomic, even if they happen via multiple events.
type XkbKeyboardDoneEvent struct{}
type XkbKeyboardDoneHandlerFunc func(XkbKeyboardDoneEvent)

// SetDoneHandler : sets handler for XkbKeyboardDoneEvent
func (i *XkbKeyboard) SetDoneHandler(f XkbKeyboardDoneHandlerFunc) {
	i.doneHandler = f
}

func (i *XkbKeyboard) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.removedHandler == nil {
			return
		}
		var e XkbKeyboardRemovedEvent

		i.removedHandler(e)
	case 1:
		if i.inputDeviceHandler == nil {
			return
		}
		var e XkbKeyboardInputDeviceEvent
		l := 0
		e.Device = i.Context().GetProxy(client.Uint32(data[l : l+4])).(*InputDevice)
		l += 4

		i.inputDeviceHandler(e)
	case 2:
		if i.layoutHandler == nil {
			return
		}
		var e XkbKeyboardLayoutEvent
		l := 0
		e.Index = client.Uint32(data[l : l+4])
		l += 4
		nameLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Name = client.String(data[l : l+nameLen])
		l += nameLen

		i.layoutHandler(e)
	case 3:
		if i.capslockEnabledHandler == nil {
			return
		}
		var e XkbKeyboardCapslockEnabledEvent

		i.capslockEnabledHandler(e)
	case 4:
		if i.capslockDisabledHandler == nil {
			return
		}
		var e XkbKeyboardCapslockDisabledEvent

		i.capslockDisabledHandler(e)
	case 5:
		if i.numlockEnabledHandler == nil {
			return
		}
		var e XkbKeyboardNumlockEnabledEvent

		i.numlockEnabledHandler(e)
	case 6:
		if i.numlockDisabledHandler == nil {
			return
		}
		var e XkbKeyboardNumlockDisabledEvent

		i.numlockDisabledHandler(e)
	case 7:
		if i.doneHandler == nil {
			return
		}
		var e XkbKeyboardDoneEvent

		i.doneHandler(e)
	}
}
