// Generated by go-wayland-scanner
// Generator revision: github.com/MatthiasKunnen/go-wayland@412de804cb23568a899c4ad2f6b8408b38184e9c
// River XML provenance: river v0.4.8 (c4b5f706314555f4846e25b8d3635631387b3fdd), protocol/river-input-management-v1.xml
// https://github.com/MatthiasKunnen/go-wayland/cmd/go-wayland-scanner
// XML file : internal/riverxkb/protocol/river-input-management-v1.xml
//
// river_input_management_v1 Protocol Copyright:
//
// SPDX-FileCopyrightText: © 2025 Isaac Freund
// SPDX-License-Identifier: MIT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

package riverxkb

import "github.com/MatthiasKunnen/go-wayland/wayland/client"

// InputManagerInterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const InputManagerInterfaceName = "river_input_manager_v1"

// InputManager : input manager global interface
//
// Input manager global interface.
type InputManager struct {
	client.BaseProxy
	finishedHandler    InputManagerFinishedHandlerFunc
	inputDeviceHandler InputManagerInputDeviceHandlerFunc
}

// NewInputManager : input manager global interface
//
// Input manager global interface.
func NewInputManager(ctx *client.Context) *InputManager {
	riverInputManagerV1 := &InputManager{}
	ctx.Register(riverInputManagerV1)
	return riverInputManagerV1
}

// Stop : stop sending events
//
// This request indicates that the client no longer wishes to receive
// events on this object.
//
// The Wayland protocol is asynchronous, which means the server may send
// further events until the stop request is processed. The client must wait
// for a river_input_manager_v1.finished event before destroying this
// object.
func (i *InputManager) Stop() error {
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Destroy : destroy the river_input_manager_v1 object
//
// This request should be called after the finished event has been received
// to complete destruction of the object.
//
// It is a protocol error to make this request before the finished event
// has been received.
//
// If a client wishes to destroy this object it should send a
// river_input_manager_v1.stop request and wait for a
// river_input_manager_v1.finished event. Once the finished event is
// received it is safe to destroy this object and any other objects created
// through this interface.
func (i *InputManager) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// CreateSeat : create a new seat
//
// Create a new seat with the given name. Has no effect if a seat with the
// given name already exists.
//
// The default seat with name "default" always exists and does not need to
// be explicitly created.
func (i *InputManager) CreateSeat(name string) error {
	const opcode = 2
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// DestroySeat : destroy a seat
//
// Destroy the seat with the given name. Has no effect if a seat with the
// given name does not exist.
//
// The default seat with name "default" cannot be destroyed and attempting
// to destroy it will have no effect.
//
// Any input devices assigned to the destroyed seat at the time of
// destruction are assigned to the default seat.
func (i *InputManager) DestroySeat(name string) error {
	const opcode = 3
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

type InputManagerError uint32

// InputManagerError :
const (
	InputManagerErrorInvalidDestroy InputManagerError = 0
)

func (e InputManagerError) Name() string {
	switch e {
	case InputManagerErrorInvalidDestroy:
		return "invalid_destroy"
	default:
		return ""
	}
}

func (e InputManagerError) Value() string {
	switch e {
	case InputManagerErrorInvalidDestroy:
		return "0"
	default:
		return ""
	}
}

func (e InputManagerError) String() string {
	return e.Name() + "=" + e.Value()
}

// InputManagerFinishedEvent : the server has finished with the input manager
//
// This event indicates that the server will send no further events on this
// object. The client should destroy the object. See
// river_input_manager_v1.destroy for more information.
type InputManagerFinishedEvent struct{}
type InputManagerFinishedHandlerFunc func(InputManagerFinishedEvent)

// SetFinishedHandler : sets handler for InputManagerFinishedEvent
func (i *InputManager) SetFinishedHandler(f InputManagerFinishedHandlerFunc) {
	i.finishedHandler = f
}

// InputManagerInputDeviceEvent : new input device
//
// A new input device has been created.
type InputManagerInputDeviceEvent struct {
	Id *InputDevice
}
type InputManagerInputDeviceHandlerFunc func(InputManagerInputDeviceEvent)

// SetInputDeviceHandler : sets handler for InputManagerInputDeviceEvent
func (i *InputManager) SetInputDeviceHandler(f InputManagerInputDeviceHandlerFunc) {
	i.inputDeviceHandler = f
}

func (i *InputManager) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.finishedHandler == nil {
			return
		}
		var e InputManagerFinishedEvent

		i.finishedHandler(e)
	case 1:
		if i.inputDeviceHandler == nil {
			return
		}
		var e InputManagerInputDeviceEvent
		l := 0
		e.Id = newInputDevice(i.Context(), client.Uint32(data[l:l+4]))
		l += 4

		i.inputDeviceHandler(e)
	}
}

// InputDeviceInterfaceName is the name of the interface as it appears in the [client.Registry].
// It can be used to match the [client.RegistryGlobalEvent.Interface] in the
// [Registry.SetGlobalHandler] and can be used in [Registry.Bind] if this applies.
const InputDeviceInterfaceName = "river_input_device_v1"

// InputDevice : an input device
//
// An input device represents a physical keyboard, mouse, touchscreen, or
// drawing tablet tool. It is assigned to exactly one seat at a time.
// By default, all input devices are assigned to the default seat.
type InputDevice struct {
	client.BaseProxy
	removedHandler InputDeviceRemovedHandlerFunc
	typeHandler    InputDeviceTypeHandlerFunc
	nameHandler    InputDeviceNameHandlerFunc
	doneHandler    InputDeviceDoneHandlerFunc
}

// NewInputDevice : an input device
//
// An input device represents a physical keyboard, mouse, touchscreen, or
// drawing tablet tool. It is assigned to exactly one seat at a time.
// By default, all input devices are assigned to the default seat.
func NewInputDevice(ctx *client.Context) *InputDevice {
	riverInputDeviceV1 := &InputDevice{}
	ctx.Register(riverInputDeviceV1)
	return riverInputDeviceV1
}

// Destroy : destroy the input device object
//
// This request indicates that the client will no longer use the input
// device object and that it may be safely destroyed.
func (i *InputDevice) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AssignToSeat : assign the input device to a seat
//
// Assign the input device to a seat. All input devices not explicitly
// assigned to a seat are considered assigned to the default seat.
//
// Has no effect if a seat with the given name does not exist.
//
//	name: name of the seat
func (i *InputDevice) AssignToSeat(name string) error {
	const opcode = 1
	nameLen := client.PaddedLen(len(name) + 1)
	_reqBufLen := 8 + (4 + nameLen)
	_reqBuf := make([]byte, _reqBufLen)
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutString(_reqBuf[l:l+(4+nameLen)], name)
	l += (4 + nameLen)
	err := i.Context().WriteMsg(_reqBuf, nil)
	return err
}

// SetRepeatInfo : set keyboard repeat rate and delay
//
// Set repeat rate and delay for a keyboard input device. Has no effect if
// the device is not a keyboard.
//
// Negative values for either rate or delay are illegal. A rate of zero
// will disable any repeating (regardless of the value of delay).
//
//	rate: rate in key repeats per second
//	delay: delay in milliseconds
func (i *InputDevice) SetRepeatInfo(rate, delay int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(rate))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(delay))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetScrollFactor : set scroll factor
//
// Set the scroll factor for a pointer input device. Has no effect if the
// device is not a pointer.
//
// For example, a factor of 0.5 will make scrolling twice as slow while a
// factor of 3.0 will make scrolling 3 times as fast.
//
// Setting a scroll factor less than 0 is a protocol error.
func (i *InputDevice) SetScrollFactor(factor float64) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutFixed(_reqBuf[l:l+4], factor)
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// MapToOutput : map input device to the given output
//
// Map the input device to the given output. Has no effect if the device is
// not a pointer, touch, or tablet device.
//
// If mapped to both an output and a rectangle, the rectangle has priority.
//
// Passing null clears an existing mapping.
func (i *InputDevice) MapToOutput(output *client.Output) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	if output == nil {
		client.PutUint32(_reqBuf[l:l+4], 0)
		l += 4
	} else {
		client.PutUint32(_reqBuf[l:l+4], output.ID())
		l += 4
	}
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// MapToRectangle : map input device to the given rectangle
//
// Map the input device to the given rectangle in the global compositor
// coordinate space. Has no effect if the device is not a pointer, touch,
// or tablet device.
//
// If mapped to both an output and a rectangle, the rectangle has priority.
//
// Width and height must be greater than or equal to 0.
//
// Passing 0 for width or height clears an existing mapping.
func (i *InputDevice) MapToRectangle(x, y, width, height int32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type InputDeviceError uint32

// InputDeviceError :
const (
	InputDeviceErrorInvalidRepeatInfo     InputDeviceError = 0
	InputDeviceErrorInvalidScrollFactor   InputDeviceError = 1
	InputDeviceErrorInvalidMapToRectangle InputDeviceError = 2
)

func (e InputDeviceError) Name() string {
	switch e {
	case InputDeviceErrorInvalidRepeatInfo:
		return "invalid_repeat_info"
	case InputDeviceErrorInvalidScrollFactor:
		return "invalid_scroll_factor"
	case InputDeviceErrorInvalidMapToRectangle:
		return "invalid_map_to_rectangle"
	default:
		return ""
	}
}

func (e InputDeviceError) Value() string {
	switch e {
	case InputDeviceErrorInvalidRepeatInfo:
		return "0"
	case InputDeviceErrorInvalidScrollFactor:
		return "1"
	case InputDeviceErrorInvalidMapToRectangle:
		return "2"
	default:
		return ""
	}
}

func (e InputDeviceError) String() string {
	return e.Name() + "=" + e.Value()
}

type InputDeviceType uint32

// InputDeviceType :
const (
	InputDeviceTypeKeyboard InputDeviceType = 0
	InputDeviceTypePointer  InputDeviceType = 1
	InputDeviceTypeTouch    InputDeviceType = 2
	InputDeviceTypeTablet   InputDeviceType = 3
)

func (e InputDeviceType) Name() string {
	switch e {
	case InputDeviceTypeKeyboard:
		return "keyboard"
	case InputDeviceTypePointer:
		return "pointer"
	case InputDeviceTypeTouch:
		return "touch"
	case InputDeviceTypeTablet:
		return "tablet"
	default:
		return ""
	}
}

func (e InputDeviceType) Value() string {
	switch e {
	case InputDeviceTypeKeyboard:
		return "0"
	case InputDeviceTypePointer:
		return "1"
	case InputDeviceTypeTouch:
		return "2"
	case InputDeviceTypeTablet:
		return "3"
	default:
		return ""
	}
}

func (e InputDeviceType) String() string {
	return e.Name() + "=" + e.Value()
}

// InputDeviceRemovedEvent : the input device is removed
//
// This event indicates that the input device has been removed.
//
// The server will send no further events on this object and ignore any
// request (other than river_input_device_v1.destroy) made after this event is
// sent. The client should destroy this object with the
// river_input_device_v1.destroy request to free up resources.
type InputDeviceRemovedEvent struct{}
type InputDeviceRemovedHandlerFunc func(InputDeviceRemovedEvent)

// SetRemovedHandler : sets handler for InputDeviceRemovedEvent
func (i *InputDevice) SetRemovedHandler(f InputDeviceRemovedHandlerFunc) {
	i.removedHandler = f
}

// InputDeviceTypeEvent : the type of the input device
//
// The type of the input device. This event is sent once when the
// river_input_device_v1 object is created. The device type cannot
// change during the lifetime of the object.
type InputDeviceTypeEvent struct {
	Type uint32
}
type InputDeviceTypeHandlerFunc func(InputDeviceTypeEvent)

// SetTypeHandler : sets handler for InputDeviceTypeEvent
func (i *InputDevice) SetTypeHandler(f InputDeviceTypeHandlerFunc) {
	i.typeHandler = f
}

// InputDeviceNameEvent : the name of the input device
//
// The name of the input device. This event is sent once when the
// river_input_device_v1 object is created. The device name cannot
// change during the lifetime of the object.
type InputDeviceNameEvent struct {
	Name string
}
type InputDeviceNameHandlerFunc func(InputDeviceNameEvent)

// SetNameHandler : sets handler for InputDeviceNameEvent
func (i *InputDevice) SetNameHandler(f InputDeviceNameHandlerFunc) {
	i.nameHandler = f
}

// InputDeviceDoneEvent : all information has been sent
//
// This event is sent after all information about the input device has
// been sent.
//
// This allows changes to one or more river_input_device_v1 properties to
// be seen as atomic, even if they happen via multiple events.
type InputDeviceDoneEvent struct{}
type InputDeviceDoneHandlerFunc func(InputDeviceDoneEvent)

// SetDoneHandler : sets handler for InputDeviceDoneEvent
func (i *InputDevice) SetDoneHandler(f InputDeviceDoneHandlerFunc) {
	i.doneHandler = f
}

func (i *InputDevice) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.removedHandler == nil {
			return
		}
		var e InputDeviceRemovedEvent

		i.removedHandler(e)
	case 1:
		if i.typeHandler == nil {
			return
		}
		var e InputDeviceTypeEvent
		l := 0
		e.Type = client.Uint32(data[l : l+4])
		l += 4

		i.typeHandler(e)
	case 2:
		if i.nameHandler == nil {
			return
		}
		var e InputDeviceNameEvent
		l := 0
		nameLen := client.PaddedLen(int(client.Uint32(data[l : l+4])))
		l += 4
		e.Name = client.String(data[l : l+nameLen])
		l += nameLen

		i.nameHandler(e)
	case 3:
		if i.doneHandler == nil {
			return
		}
		var e InputDeviceDoneEvent

		i.doneHandler(e)
	}
}
