#!/bin/sh
set -eu

wpctl_output=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)
volume=$(printf '%s\n' "$wpctl_output" | awk '{ printf "%.0f", $2 * 100 }')
muted_label=$(printf '%s\n' "$wpctl_output" | awk '{ print $3 }')

notify-send -t 1500 -a 'ya-vol' -h "string:value:$muted_label" \
  -h "int:value:$volume" "Microphone: ${volume}% ${muted_label}"
